<?php

namespace Dywee\TicketBundle\Repository;

use Gedmo\Tree\Entity\Repository\NestedTreeRepository;

/**
 * TicketCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketCategoryRepository extends NestedTreeRepository
{
    public function myFindByHandledBy($user)
    {
        $qb = $this->createQueryBuilder('tc')
            ->select('tc')
            ->join('tc.tickets', 't')
            ->addSelect('t')
            ->where('t.handledBy = :user')
            ->setParameters(array('user' => $user));

        $query = $qb->getQuery();

        return $query->getResult();
    }
}
