<?php

namespace Dywee\TicketBundle\Repository;

/**
 * TicketStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketStateRepository extends \Doctrine\ORM\EntityRepository
{
}
